version: "3"
services:
       auth-app:
           container_name: auth_app
           image: auth_app/auth_app
           restart: always
           build: .
           ports:
             - "7500:7500"
           links:
             - mongo
       mongo:
             container_name: mongo
             image: mongo
             volumes:
               - ./data/db:/data/db
             ports:
               - '27017:27017'